config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resource :search, only: [:show]
  resources :groups, only: [:new, :create, :show, :index] do
    resources :memberships, only: [:new, :create, :destroy]
    resources :messages, only: [:new, :create, :destroy]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :messages

  has_many :memberships
  has_many :users, through: :memberships

  has_many :admin_memberships, -> { where admin: true },
                                     class_name: "Membership"
  has_many :admins, through: :admin_memberships, source: "user"

  def add_user(new_user)
    users << new_user
  end

  def remove_member(member)
    users.destroy(member)
  end

  def non_admin_users
    admins - users
  end

  def messages_desc
    messages.order(:created_at)
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  def make_admin
    self.admin = true
    save
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :messages

  has_many :memberships
  has_many :groups, through: :memberships

  def member?(group)
    group.users.include?(self)
  end

  def admin_of_group?(group)
    membership = find_membership(group)
    membership.admin?
  end

  def group_membership(group)
    find_membership(group)
  end

  private

  def find_membership(group)
    Membership.where(user: self, group: group).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_is_admin_of_group
    membership = Membership.where(user: current_user, group: find_group).first
    membership.admin?
  end

  private

  def find_group
    Group.find(params[:group_id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @groups = current_user.groups
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def show
    @group = find_group
  end

  def create
    @group = Group.new(group_params)
    @group.add_user(current_user)

    if @group.save
      membership = @group.memberships.take
      membership.make_admin
      redirect_to @group
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end

  def find_group
    Group.find(params[:id])
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :user_belongs_to_group, only: [:destroy]
  def new
  end

  def create
    @group = find_group
    @group.add_user(current_user)

    redirect_to @group
  end

  def destroy
    membership = Membership.find(params[:id])
    @group = membership.group
    @group.remove_member(current_user)

    redirect_to @group
  end

  private

  def find_group
    @group ||= Group.find(params[:group_id])
  end

  def user_belongs_to_group
    unless current_user.member?(find_group)
      redirect_to :back
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :user_is_admin_of_group, only: [:destroy]
  def new
    group = find_group
    @message = group.messages.new
  end

  def create
    group = find_group
    @message = group.messages.new(message_params)
    @message.user = current_user

    if @message.save
      redirect_to group_path(group)
    else
      render new
    end
  end

  def destroy
    message = find_message
    @group = message.group
    message.destroy

    redirect_to @group
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def find_group
    Group.find(params[:group_id])
  end

  def find_message
    Message.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @groups = Group.where("name ILIKE ?", "%#{params[:search]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/dashboards/show.html.erb
<h1> My Groups </h1>
<%= link_to "Create Group", new_group_path %>

<div class="groups">
  <ul>
    <%= render @groups %>
  </ul>
</div>

app/views/form_errors/_errors.html.erb
<div>
  <% if object.errors.any? %>
    <%= pluralize(object.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% object.errors.full_messages.each do |error_message| %>
        <li><%= error_message %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/groups/_group.html.erb
<li>
  <h3><%= link_to group.name, group_path(group) %></h3>
  <p><%= group.description %></p>
  <p> Members: <%= group.users.length %></p>
</li>

app/views/groups/new.html.erb
<div>
  <H2> New Group </H2>

  <%= render partial: "form_errors/errors", locals: {object: @group} %>

  <%= form_for @group do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
    <div>
      <%= form.submit "Create" %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1> <%= @group.name %> </h1>
<h3> <%= @group.description %> </h3>

<div>
  <% if current_user.member?(@group) %>
    <%= link_to "Leave Group", group_membership_path(@group, current_user.group_membership(@group)), method: :delete %>
  <% else %>
    <%= link_to "Join Group", group_memberships_path(@group), method: :post %>
  <% end %>
</div>

<aside>
  <fieldset>
    <h3> Members </h3>
    <div class="members">
      <ul>
        <%= render partial: "users/admin", collection: @group.admins %>
      </ul>
      <ul>
        <%= render partial: @group.non_admin_users, locals: {group: @group} %>
      </ul>
    </div>
  </fieldset>
</aside>

<%= link_to "New Message", new_group_message_path(@group) %>

<div>
  <%= render partial: @group.messages_desc, locals: {group: @group} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>

  <% if signed_in? %>
    <%= current_user.email %>
    <%= link_to "My dashboard", dashboard_path %>
    <%= link_to "Sign out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_session_path %>
    <%= link_to "Sign up", new_user_path %>
  <% end %>

  <%= render partial: "searches/search_bar" %>
</head>

<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-header">
    <h5><%= message.user.username %> </h5>
    <% if current_user.admin_of_group?(group) %>
      <%= button_to "Remove Message",
                                     group_message_path(group, message),
                                     method: :delete, class:"button" %>
    <% end %>
  </div>
  <div class="message-content">
    <%= message.content %>
  </div>
</div>

app/views/messages/new.html.erb
<h1> New Message </h1>

<%= render partial: "form_errors/errors", locals: {object: @message} %>

<div>
  <%= form_for @message, url: group_messages_url(@message.group) do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit "Post" %>

  <% end %>
</div>

app/views/searches/_search_bar.html.erb
<div>
  <%= form_tag search_path, method: :get do %>
    <%= search_field_tag :search, params[:search], placeholder: "search for groups" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

app/views/searches/show.html.erb
<h1> Groups </h1>
<div class="groups">
  <ul>
    <%= render @groups, paginate: true, size: 12 %>
  </ul>
</div>

app/views/users/_admin.html.erb
<p> <%= admin.username %> Admin </p>

app/views/users/_user.html.erb
<%= user.username %>
<% if current_user.admin_of_group?(group) %>
  <%= button_to "Kick User", group_membership_path(group, user.group_membership(@group)), method: :delete %>
<% end %>

app/views/users/new.html.erb
<div>
  <h3>
  <p> Welcome to gitRankr</p>
  </h3>
  <p> All ready have an account sign in here
    <%= link_to "Sign In", new_session_path %>
  </p>
</div>

<%= form_for @user do |form| %>

  <%= render partial: "form_errors/errors", locals: {object: @user} %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>